import agentImages from "@/lib/generated/agent-images.json";
import assetManifest from "@/lib/generated/asset-manifest.json";

export const AGENT_TYPES = ["automation", "support", "prospection", "content", "data"] as const;
export type AgentType = (typeof AGENT_TYPES)[number];

export interface AgentDefinition {
  type: AgentType;
  label: string;
  /** 2.5D fallback (temporary): transparent cut-out generated by `npm run assets:agents`. */
  image: string;
  avatar: string;
  aspect: number;
  /**
   * Production asset: public/models/agents/<type>.glb (rigged, idle clip named "idle").
   * Picked automatically when present — see scripts/asset-manifest.mjs.
   */
  model: string | null;
}

const hasModel = (type: AgentType) => (assetManifest.agents as string[]).includes(type);

const define = (type: AgentType, label: string): AgentDefinition => ({
  type,
  label,
  image: `/images/agents/${type}.webp`,
  avatar: `/images/agents/${type}-avatar.webp`,
  aspect: agentImages[type].aspect,
  model: hasModel(type) ? `/models/agents/${type}.glb` : null,
});

export const AGENTS: Record<AgentType, AgentDefinition> = {
  automation: define("automation", "Automatisation"),
  support: define("support", "Support client"),
  prospection: define("prospection", "Prospection"),
  content: define("content", "Création de contenu"),
  data: define("data", "Analyse de données"),
};
