// Brand logo pipeline. Source of truth: design/brand/logo-vector.svg (the designer's file).
// Writes public/images/brand/d2s-aigency.svg (site loader mask + 3D signage) and lib/generated/logo.ts
// (inline, animated header logo). Run: node scripts/build-logo.mjs
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const src = readFileSync(path.join(root, "design/brand/logo-vector.svg"), "utf8");

const [, vx, vy, vw, vh] = src.match(/viewBox="([-\d.]+)\s+([-\d.]+)\s+([-\d.]+)\s+([-\d.]+)"/).map(Number);
const defs = src.match(/<defs>([\s\S]*?)<\/defs>/)[1].trim();
const paths = [...src.matchAll(/<path\b([\s\S]*?)\/>/g)].map((m) => {
  const attrs = m[1];
  const get = (name) => (attrs.match(new RegExp(`${name}="([^"]*)"`)) ?? [])[1];
  return { d: get("d"), fill: get("fill"), stroke: get("stroke"), strokeOpacity: get("stroke-opacity"), strokeWidth: get("stroke-width") };
});
if (paths.length !== 3) throw new Error(`expected 3 paths (mark, ai, wordmark), found ${paths.length}`);
const [mark, ai, wordmark] = paths;

/** Box of a path, used to place the light sweep over the "AI". */
const box = (d) => {
  const n = d.match(/-?\d+(\.\d+)?/g).map(Number);
  const xs = n.filter((_, i) => i % 2 === 0);
  const ys = n.filter((_, i) => i % 2 === 1);
  return { x: Math.min(...xs), y: Math.min(...ys), width: Math.max(...xs) - Math.min(...xs), height: Math.max(...ys) - Math.min(...ys) };
};

const geometry = {
  viewBox: { x: vx, y: vy, width: vw, height: vh },
  defs,
  mark,
  ai,
  wordmark,
  aiBox: box(ai.d),
};

mkdirSync(path.join(root, "lib/generated"), { recursive: true });
writeFileSync(
  path.join(root, "lib/generated/logo.ts"),
  `// Generated by scripts/build-logo.mjs from design/brand/logo-vector.svg — do not edit by hand.\n` +
    `export const LOGO = ${JSON.stringify(geometry, null, 2)} as const;\n`,
);
writeFileSync(path.join(root, "public/images/brand/d2s-aigency.svg"), src);
console.log(`logo: viewBox ${vx} ${vy} ${vw} ${vh} · AI box ${JSON.stringify(geometry.aiBox)}`);
